### ISSUE TITLE
BTH Electrum. -->3.2.1 not syncing from block 565554 and dates showing not verified as shown in picture

### ISSUE THREAD

**Issue by sathebm** [BTHPOS/electrum#4]
3.2.1 not syncing from block 565554 and dates showing not verified as shown in picture
![image](https://user-images.githubusercontent.com/35578406/50907978-b351d500-144e-11e9-816a-8d12c9aa6521.png)

**Comment by dondreytaylor** [comment]
Thank you for bringing this issue to our attention. We just put out a fix for this in [ElectrumBTH version 1.2.](https://github.com/BTHPOS/electrum/releases/tag/v1.2) This should allow you to sync beyond block 565554.

**Comment by dondreytaylor** [comment]
Let me know if you have any additional issues. We have not yet heard any reports of version 1.2 failing to sync. Closing for now.

**Comment by sathebm** [comment]
Its done, Thanks
